# -*- coding: utf-8 -*-
"""Segunda entrega.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvLr7F5A6YTUPV3g6M3q7HdcXL_JQ7-U
"""

import numpy as np

temperaturas = np.array([2.5, 3.2, 5.1, 6.3, 7.0, 8.1, 10.5, 9.8, 8.5, 7.3,
    6.2, 5.1, 4.5, 3.8, 5.6, 6.7, 7.2, 8.3, 10.1, 9.4,
    8.2, 7.0, 6.3, 5.4, 4.7, 3.9, 5.8, 6.9, 7.4, 8.5,
    10.3, 9.6, 8.4, 7.2, 6.5, 5.6, 4.9, 4.1, 5.9, 7.0,
    7.5, 8.6, 10.4, 9.7, 8.5, 7.3, 6.6, 5.7, 5.0, 4.2,
    6.0, 7.1, 7.6, 8.7, 10.6, 9.9, 8.7, 7.5, 6.8, 5.9,
    5.2, 4.4, 6.1, 7.2, 7.7, 8.8, 10.7, 10.0, 8.8, 7.6,
    6.9, 6.0, 5.3, 4.5, 6.2, 7.3, 7.8, 8.9, 10.8, 10.2,
    9.0, 7.8, 7.1, 6.2, 5.5, 4.7, 6.3, 7.4, 7.9, 9.0,
    10.9, 10.3, 9.1, 7.9, 7.2, 6.3, 5.6, 4.8, 6.4, 7.5])

# 1 - Análise Estatística: Calcule a média, mediana e desvio padrão das temperaturas usando Numpy.

media = np.mean(temperaturas)
mediana = np.median(temperaturas)
desvioPadrao = np.std(temperaturas)

print(f"Media = {media:.2f} \nMediana = {mediana:.2f} \nDesvio padrao = {desvioPadrao:.2}")



# 2 - Classificação de Temperaturas: Classifique cada dia como "frio", "moderado" ou "quente". Você pode definir os limites para cada categoria.

diasFrios = (temperaturas < 5.0)
diasModerados = (temperaturas >= 5.0) & (temperaturas < 10.0)
diasQuentes = (temperaturas >= 10.0)

print(f"Temperaturas frias: {temperaturas[diasFrios]}\nTemperaturas moderadas:{temperaturas[diasModerados]}\nTemperaturas quentes: {temperaturas[diasQuentes]}")


# 3 - Dias Extremos: Identifique os dias mais frios e mais quentes do ano.

diaMaisFrio = np.min(temperaturas)
diaMaisQuente = np.max(temperaturas)

diaF = np.where(temperaturas == diaMaisFrio)[0][0]
diaQ = np.where(temperaturas == diaMaisQuente)[0][0]

print(f"A menor temperatura foi: {diaMaisFrio}; ela ocorreu no dia {diaF +1}\nA maior temperatura foi: {diaMaisQuente}; ela ocorreu no dia {diaQ +1}")